CREATE TABLE USERS(
	Email       VARCHAR(50)    NOT NULL    UNIQUE,
    password_digest    CHAR(60)      NOT NULL,
    User_type		SMALLINT	   NOT NULL,
    PRIMARY KEY(Email)
);

CREATE TABLE ORGANIZATION(
    Email       VARCHAR(50)    NOT NULL    UNIQUE,
    Name        VARCHAR(75)    NOT NULL,
    Phone_no     CHAR(10)       NOT NULL,
    Address     VARCHAR(100),
    City        VARCHAR(100),
    State       CHAR(2),
    Zip_code     CHAR(5),
    Description VARCHAR(500),
    Approved    BOOL           NOT NULL,
    PRIMARY KEY(Email),
    FOREIGN KEY(Email) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ORGANIZATION_CATEGORY(
	Email       VARCHAR(50)     NOT NULL,
	Category    VARCHAR(100)    NOT NULL,
	PRIMARY KEY(Email, Category),
	FOREIGN KEY(Email) REFERENCES ORGANIZATION(Email) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE VOLUNTEER(
    Email       VARCHAR(50)    NOT NULL    UNIQUE,
    Verified    BOOL           NOT NULL,
    PRIMARY KEY(Email),
    FOREIGN KEY(Email) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OPPORTUNITY(
    Id             SERIAL          NOT NULL,
    Name           VARCHAR(50)     NOT NULL,
    Address        VARCHAR(100)    NOT NULL,
    City           VARCHAR(100)    NOT NULL,
    State          CHAR(2)         NOT NULL,
    Zip_code        CHAR(5)         NOT NULL,
    Transportation BOOLEAN         NOT NULL,
    Description    VARCHAR(500)    NOT NULL,
    Frequency      VARCHAR(50),
    Email          VARCHAR(50)     NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY(Email) REFERENCES ORGANIZATION(Email) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE EVENT_DATE(
	Id      INTEGER      NOT NULL,
	On_date  DATE        NOT NULL,
	Start_time    TIME WITHOUT TIMEZONE,
	Start_time    TIME WITHOUT TIMEZONE,
	PRIMARY KEY(Id, On_date),
	FOREIGN KEY(Id) REFERENCES OPPORTUNITY(Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE FORM(
	Id	        INTEGER		   NOT NULL,
	Link_path        VARCHAR(50)    NOT NULL,
    PRIMARY KEY(Id, Link_path),
    FOREIGN KEY(Id) REFERENCES OPPORTUNITY(Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SKILL(
    Id       INTEGER          NOT NULL,
	Skill    VARCHAR(100)    NOT NULL,
	PRIMARY KEY(Id, Skill),
	FOREIGN KEY(Id) REFERENCES OPPORTUNITY(Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OPPORTUNITY_CATEGORY(
	Id          INTEGER          NOT NULL,
	Category    VARCHAR(100)    NOT NULL,
	PRIMARY KEY(Id, Category),
	FOREIGN KEY(Id) REFERENCES OPPORTUNITY(Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE BOOKMARK(
    Email       VARCHAR(50)    NOT NULL,
    Id          INTEGER         NOT NULL,
	PRIMARY KEY(Email, Id),
	FOREIGN KEY(Email) REFERENCES USER(Email) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Id) REFERENCES OPPORTUNITY(Id) ON UPDATE CASCADE ON DELETE CASCADE
);
